Repository bitia-ru/melq, pull requests merged in 2020-07, with the labels that each got.

#75 MELQ-74: Подключить focus-visible
  frontend/index.html
  frontend/src/v1/index.css
Labels: enhancement

#77 MELQ-76: Поправить Tooltip
  frontend/src/v1/components/Tooltip/Tooltip.jsx
  frontend/src/v1/examples/TooltipExample.js
  frontend/src/v1/utils/conditionalWrapper.js
Labels: enhancement

#48 MELQ-46: Add Counter component
  frontend/src/v1/components/Counter/Counter.jsx
  frontend/src/v1/components/Counter/CounterLayout.jsx
  frontend/src/v1/components/icon_counters/CommentCounter/CommentCounter.jsx
  frontend/src/v1/components/icon_counters/CommentCounter/assets/comment.svg
  frontend/src/v1/components/icon_counters/LikeCounter/LikeCounter.jsx
  frontend/src/v1/components/icon_counters/LikeCounter/assets/like.svg
  frontend/src/v1/components/icon_counters/ShareCounter/ShareCounter.jsx
  frontend/src/v1/components/icon_counters/ShareCounter/assets/share.svg
  frontend/src/v1/components/icon_counters/ViewCounter/ViewCounter.jsx
  frontend/src/v1/components/icon_counters/ViewCounter/assets/view.svg
  frontend/src/v1/examples/CounterExample.js
  frontend/src/v1/examples/index.js
  frontend/src/v1/theme.js
Labels: enhancement

#98 MELQ-95: Задать параметры шрифта для Tooltip
  frontend/src/v1/components/Tooltip/Tooltip.jsx
  frontend/src/v1/theme.js
Labels: bug

#47 MELQ-45: Add Switch component
  frontend/src/v1/components/Switch/Switch.jsx
  frontend/src/v1/components/Switch/SwitchLayout.jsx
  frontend/src/v1/examples/SwitchExample.js
  frontend/src/v1/examples/index.js
Labels: enhancement

#79 MELQ-63: Сделать компонент PostCard
  frontend/src/v1/components/Card/Card.jsx
  frontend/src/v1/components/PostCard/PostCard.jsx
  frontend/src/v1/components/PostCard/PostCardLayout.jsx
  frontend/src/v1/examples/PostCardExample.js
  frontend/src/v1/examples/images/postCard_demo_image.png
  frontend/src/v1/examples/index.js
  frontend/src/v1/theme.js
Labels: enhancement

#100 MELQ-99: Introduce ImageIcon
  frontend/src/v1/components/ImageIcon/ImageIcon.jsx
  frontend/src/v1/components/ImageIcon/ImageIconLayout.jsx
  frontend/src/v1/components/ImageIcon/images/image.svg
  frontend/src/v1/examples/ImageIconExample.js
  frontend/src/v1/examples/images/demo_image_icon.jpg
  frontend/src/v1/examples/index.js
Labels: feature

#94 MELQ-93: Сделать полноценный компонент AvatarRound взамен временного
  frontend/src/v1/components/AvatarRound/AvatarRound.js
  frontend/src/v1/components/AvatarRound/AvatarRound.jsx
  frontend/src/v1/components/AvatarRound/AvatarRoundLayout.jsx
  frontend/src/v1/components/AvatarRound/images/avatar.svg
  frontend/src/v1/components/Comment/Comment.js
  frontend/src/v1/examples/AvatarRoundExample.js
  frontend/src/v1/examples/images/demo_avatar.png
  frontend/src/v1/examples/index.js
Labels: enhancement

#91 MELQ-90: Сделать компонент TextArea
  frontend/src/v1/components/TextArea/TextArea.jsx
  frontend/src/v1/components/TextArea/TextAreaLayout.jsx
  frontend/src/v1/components/TextArea/images/photo.svg
  frontend/src/v1/examples/TextAreaExample.js
  frontend/src/v1/examples/index.js
  frontend/src/v1/index.css
Labels: feature

#109 MELQ-105: Добавить два размера для шрифта GilroyRegular в theme.js
  frontend/src/v1/theme.js
Labels: enhancement

#84 MELQ-83: Сделать компонент Item
  frontend/src/v1/components/Item/Item.jsx
  frontend/src/v1/components/Item/ItemLayout.jsx
  frontend/src/v1/examples/ItemExample.js
  frontend/src/v1/examples/images/demoItemIcon.png
  frontend/src/v1/examples/images/demoLanguageItemIcon.png
  frontend/src/v1/examples/index.js
Labels: feature

#87 MELQ-86: Сделать компонент List
  frontend/src/v1/components/List/List.jsx
  frontend/src/v1/components/List/ListLayout.jsx
  frontend/src/v1/examples/ItemExample.js
  frontend/src/v1/examples/ListExample.js
  frontend/src/v1/examples/images/demoLanguageItemIconEn.png
  frontend/src/v1/examples/images/demoLanguageItemIconRu.png
  frontend/src/v1/examples/index.js
Labels: feature

#97 MELQ-96: Сделать компонент LanguageSelect
  frontend/src/v1/components/LanguageSelect/LanguageSelect.jsx
  frontend/src/v1/components/LanguageSelect/LanguageSelectLayout.jsx
  frontend/src/v1/components/LanguageSelect/images/en.png
  frontend/src/v1/components/LanguageSelect/images/ru.png
  frontend/src/v1/examples/LanguageSelectExample.js
  frontend/src/v1/examples/index.js
Labels: feature

#89 MELQ-88: Сделать компонент Input
  frontend/src/v1/components/Input/Input.jsx
  frontend/src/v1/components/Input/InputLayout.jsx
  frontend/src/v1/examples/InputExample.js
  frontend/src/v1/examples/index.js
Labels: feature

#92 MELQ-71: List links to UI kit components in `/components`
  frontend/src/v1/V1.jsx
  frontend/src/v1/examples/Main.js
Labels: enhancement

#61 MELQ-59: Сделать компонент Link
  frontend/src/v1/components/Link/Link.jsx
  frontend/src/v1/components/Link/LinkLayout.jsx
  frontend/src/v1/components/Link/images/preview.svg
  frontend/src/v1/components/Link/images/trash.svg
  frontend/src/v1/examples/LinkExample.js
  frontend/src/v1/examples/index.js
Labels: feature

#119 MELQ-116: Сделать разделение на два типа скругления border
  frontend/src/v1/theme.js
Labels: feature

#50 MELQ-49: Сделать компонент Icon
  frontend/img/settings.svg
  frontend/src/v1/components/CloseButton/CloseButton.js
  frontend/src/v1/components/Icon/Icon.jsx
  frontend/src/v1/components/Icon/IconLayout.jsx
  frontend/src/v1/components/icon_buttons/CloseButton/CloseButton.jsx
  frontend/src/v1/components/icon_buttons/CloseButton/CloseButtonLayout.jsx
  frontend/src/v1/components/icon_buttons/CloseButton/images/close.svg
  frontend/src/v1/components/icon_buttons/CopyLinkButton/CopyLinkButton.jsx
  frontend/src/v1/components/icon_buttons/CopyLinkButton/CopyLinkButtonLayout.jsx
  frontend/src/v1/components/icon_buttons/CopyLinkButton/images/copy_link.svg
  frontend/src/v1/components/icon_buttons/EditButton/EditButton.jsx
  frontend/src/v1/components/icon_buttons/EditButton/EditButtonLayout.jsx
  frontend/src/v1/components/icon_buttons/EditButton/images/edit.svg
  frontend/src/v1/components/icon_buttons/HideButton/HideButton.jsx
  frontend/src/v1/components/icon_buttons/HideButton/HideButtonLayout.jsx
  frontend/src/v1/components/icon_buttons/HideButton/images/hide.svg
  frontend/src/v1/components/icon_buttons/LogInButton/LogInButton.jsx
  frontend/src/v1/components/icon_buttons/LogInButton/LogInButtonLayout.jsx
  frontend/src/v1/components/icon_buttons/LogInButton/images/login.svg
  frontend/src/v1/components/icon_buttons/LogOutButton/LogOutButton.jsx
  frontend/src/v1/components/icon_buttons/LogOutButton/LogOutButtonLayout.jsx
  frontend/src/v1/components/icon_buttons/LogOutButton/images/logout.svg
  frontend/src/v1/components/icon_buttons/SmallCloseButton/SmallCloseButton.jsx
  frontend/src/v1/components/icon_buttons/SmallCloseButton/SmallCloseButtonLayout.jsx
  frontend/src/v1/components/icon_buttons/SmallCloseButton/images/small_close.svg
  frontend/src/v1/components/icon_buttons/TrashButton/TrashButton.jsx
  frontend/src/v1/components/icon_buttons/TrashButton/TrashButtonLayout.jsx
  frontend/src/v1/components/icon_buttons/TrashButton/images/trash.svg
  frontend/src/v1/examples/IconExample.js
  frontend/src/v1/examples/index.js
Labels: feature

#69 MELQ-67: Сделать компонент PhotoPreview
  frontend/src/v1/components/PhotoPreview/PhotoPreview.jsx
  frontend/src/v1/components/PhotoPreview/PhotoPreviewLayout.jsx
  frontend/src/v1/examples/PhotoPreviewExample.js
  frontend/src/v1/examples/images/demo_image.png
  frontend/src/v1/examples/index.js
Labels: feature

#111 MELQ-110: Сделать компонент SocialLink
  frontend/src/v1/components/SocialLink/SocialLink.jsx
  frontend/src/v1/components/SocialLink/SocialLinkLayout.jsx
  frontend/src/v1/components/social_links/FacebookIcon/FacebookIcon.jsx
  frontend/src/v1/components/social_links/FacebookIcon/assets/facebook.svg
  frontend/src/v1/components/social_links/FacebookIcon/assets/facebook_disabled.svg
  frontend/src/v1/components/social_links/GoogleIcon/GoogleIcon.jsx
  frontend/src/v1/components/social_links/GoogleIcon/assets/google.svg
  frontend/src/v1/components/social_links/GoogleIcon/assets/google_disabled.svg
  frontend/src/v1/components/social_links/InstagramIcon/InstagramIcon.jsx
  frontend/src/v1/components/social_links/InstagramIcon/assets/instagram.svg
  frontend/src/v1/components/social_links/InstagramIcon/assets/instagram_disabled.svg
  frontend/src/v1/components/social_links/VKIcon/VKIcon.jsx
  frontend/src/v1/components/social_links/VKIcon/assets/vk.svg
  frontend/src/v1/components/social_links/VKIcon/assets/vk_disabled.svg
  frontend/src/v1/examples/SocialLinkExample.js
  frontend/src/v1/examples/index.js
Labels: feature

#115 MELQ-112: Сделать компонент TextAreaWithPhotoLoader
  frontend/package-lock.json
  frontend/package.json
  frontend/src/v1/components/TextAreaWithPhotoLoader/TextAreaWithPhotoLoader.jsx
  frontend/src/v1/components/TextAreaWithPhotoLoader/TextAreaWithPhotoLoaderLayout.jsx
  frontend/src/v1/components/TextAreaWithPhotoLoader/images/photo.svg
  frontend/src/v1/examples/TextAreaWithPhotoLoaderExample.js
  frontend/src/v1/examples/index.js
Labels: feature

#38 MELQ-37: Сделать компонент Button
  frontend/src/v1/components/Button/Button.js
  frontend/src/v1/components/Button/Button.jsx
  frontend/src/v1/components/Button/ButtonLayout.jsx
  frontend/src/v1/components/Button/images/back.svg
  frontend/src/v1/components/Button/images/edit.svg
  frontend/src/v1/examples/ButtonExample.js
Labels: feature

#82 MELQ-81: Сделать компонент Error
  frontend/src/v1/components/Error/Error.jsx
  frontend/src/v1/components/Error/ErrorLayout.jsx
  frontend/src/v1/components/Error/images/error.svg
  frontend/src/v1/examples/ErrorExample.js
  frontend/src/v1/examples/index.js
Labels: feature

#42 MELQ-41: Add CheckBox component
  frontend/src/v1/components/CheckBox/CheckBox.jsx
  frontend/src/v1/components/CheckBox/CheckBoxLayout.jsx
  frontend/src/v1/components/CheckBox/assets/check.svg
  frontend/src/v1/components/CheckBox/assets/check_disabled.svg
  frontend/src/v1/components/CheckBox/assets/check_small.svg
  frontend/src/v1/components/CheckBox/assets/check_small_disabled.svg
  frontend/src/v1/components/Counter/Counter.jsx
  frontend/src/v1/examples/CheckBoxExample.js
  frontend/src/v1/examples/index.js
Labels: feature

#103 MELQ-102: Сделать компонент Select
  frontend/src/v1/components/Select/Select.jsx
  frontend/src/v1/components/Select/SelectLayout.jsx
  frontend/src/v1/components/Select/images/arrow.svg
  frontend/src/v1/examples/SelectExample.js
  frontend/src/v1/examples/index.js
Labels: feature

#118 MELQ-117: Сделать компонент Search
  frontend/src/v1/components/Icon/IconLayout.jsx
  frontend/src/v1/components/Search/Search.jsx
  frontend/src/v1/components/Search/SearchLayout.jsx
  frontend/src/v1/components/Search/assets/search.svg
  frontend/src/v1/examples/SearchExample.js
  frontend/src/v1/examples/index.js
Labels: feature

#55 MELQ-54: Introduce ReduxForm
  frontend/package-lock.json
  frontend/package.json
  frontend/src/v1/components/LogInForm/LogInForm.jsx
  frontend/src/v1/components/LogInForm/LogInFormLayout.jsx
  frontend/src/v1/components/TextArea/images/photo.svg
  frontend/src/v1/examples/LogInFormExample.js
  frontend/src/v1/examples/index.js
  frontend/src/v1/reducers.js
  frontend/src/v1/utils/validation.js
Labels: feature
